name: 'Prompt Evaluation'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  evaluate-prompt:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
 
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Promptfoo
        run: npm install -g promptfoo

      - name: Run evaluation
        run: promptfoo eval
        env:
         OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}